version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dogops-backend:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: dogops-frontend:latest