{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    release: kube-prometheus-stack # תווית חובה כדי שפרומיתיאוס יאסוף את זה!
spec:
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http # מוודא שזה תואם לשם הפורט ב-Service שלך
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}