replicaCount: 1

image:
  repository: postgres
  tag: "15-alpine"
  pullPolicy: IfNotPresent

env:
  POSTGRES_DB: "dogops"
  POSTGRES_USER: "ShaiAdmin"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

persistence:
  enabled: true
  size: "2Gi"

auth:
  existingSecret: "test-db-credentials"

serviceAccount:
  create: true
  annotations: {}
  automount: true

# --- הבלוקים החדשים שסוגרים את כל הנתקים ב-Chart ---

service:
  type: ClusterIP
  port: 5432

httpRoute:
  enabled: false
  annotations: {}
  parentRefs: []
  hostnames: []
  rules: []

ingress:
  enabled: false