replicaCount: 1

image:
  repository: 480891637713.dkr.ecr.us-east-1.amazonaws.com/devops-dogops-backend 
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ecr-registry-secret

nameOverride: ""
fullnameOverride: "devops-dogops-backend"

serviceAccount:
  create: true
  annotations: {}
  name: ""
  automount: true

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: dogops.local
      paths:
        - path: /
          pathType: ImplementationSpecific

# ==========================================
# 🚀 KUBERNETES RESOURCES & AUTOSCALING
# ==========================================
# Resource requests and limits ensure predictable performance and prevent starvation.
# The Horizontal Pod Autoscaler (HPA) uses these metrics to automatically scale
# the application replicas based on real-time traffic and CPU utilization.
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

httpRoute:
  enabled: false

# הגדרות משתני סביבה עבור ספרינט 1
# ערך ברירת מחדל גנרי - יידרס באופן אוטומטי על ידי ה-GitOps
databaseUrl: "postgresql://postgres:postgres@postgres:5432/dogops"
existingSecretName: "" # הוספנו את זה כדי לאפשר עקיפה של שם הסוד
# הוספנו כדי שה-Chart ידע לקבל את השם מה-GitOps
databaseName: "dogopsdb"
s3BucketName: "devops-dogops-images"

aws:
  irsaEnabled: true

serviceMonitor:
  enabled: true
  path: /metrics
  interval: 15s

# SSO Configuration
googleClientId: ""